require('./fault-runner.js')('../src/engine-holdem.js', 'verify-holdem.js', [
  ['eval5 漏掉轮子顺(A2345)',
   "else if (uniq[0] === 14 && uniq[1] === 5) straightHigh = 5;", ''],
  ['eval5 同花判定恒真（人人都是同花）',
   'if (suitOf(cs[i]) !== s0) sameSuit = false;', ''],
  ['eval5 分组排序漏了"张数优先"（葫芦/四条会被判错）',
   'groups.sort(function (a, b) { return b[0] - a[0] || b[1] - a[1]; });',
   'groups.sort(function (a, b) { return b[1] - a[1]; });'],
  ['eval5 顺子上下界差一（A高顺变成不是顺）',
   'if (uniq[0] - uniq[4] === 4) straightHigh = uniq[0];',
   'if (uniq[0] - uniq[4] === 5) straightHigh = uniq[0];'],
  ['牌型权重塌陷（同花顺不再天然大过四条）',
   'return ((((cat * 15 + (a || 0)) * 15 + (b || 0)) * 15 + (c || 0)) * 15 + (d || 0)) * 15 + (e || 0);',
   'return ((((cat + (a || 0)) * 15 + (b || 0)) * 15 + (c || 0)) * 15 + (d || 0)) * 15 + (e || 0);'],
  ['eval7 同花门槛写成 >=4（四张同花就判同花）',
   'for (s = 0; s < 4; s++) if (sc[s] >= 5) {', 'for (s = 0; s < 4; s++) if (sc[s] >= 4) {'],
  ['eval7 漏掉"两组三条=葫芦"',
   'if (trips.length >= 2) return pack(6, trips[0], trips[1]);                    // 两组三条 → 葫芦', ''],
  ['eval7 顺子的连续计数遇到断档不清零',
   'run = rc[r] ? run + 1 : 0;', 'run = run + 1;'],
  ['eval7 四条的踢脚把四条本身算进去',
   "for (r = 14; r >= 2; r--) if (r !== quad && rc[r] > 0) { kick = r; break; }",
   "for (r = 14; r >= 2; r--) if (rc[r] > 0) { kick = r; break; }"],
  ['eval7 漏掉轮子同花顺',
   'if (fset[5] && fset[4] && fset[3] && fset[2] && fset[14]) return pack(8, 5);   // 轮子同花顺', ''],
  ['equity 把平局全算成赢',
   'if (beaten) lose++;\n      else if (ties > 1) { tie++; tieShare += 1 / ties; }\n      else win++;',
   'if (beaten) lose++;\n      else { win++; }'],
  ['equity 平分只按一份算（不除以并列人数）',
   'else if (ties > 1) { tie++; tieShare += 1 / ties; }',
   'else if (ties > 1) { tie++; tieShare += 1; }'],
  ['equity 给对手发牌的偏移写错（和公共牌用同一批牌）',
   'var oh = oppKnown ? oppKnown[i] : [d[needBoard + i * 2], d[needBoard + i * 2 + 1]];',
   'var oh = oppKnown ? oppKnown[i] : [d[i * 2], d[i * 2 + 1]];'],
  ['equity 不查重复牌（同一张牌能出现两次）',
   'if (known[i] < 0 || known[i] > 51 || used[known[i]]) return null;   // 非法或重复',
   'if (known[i] < 0 || known[i] > 51) return null;'],
]);
